version: "3.9"
networks:
  my-network:
    name: commonspaces
    driver: bridge
    external: true 
services:
  tmra-sendmail-tmra-ai:
    networks:
      - my-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m
    env: 
      - PORT=5174
      - SOURCE_EMAIL='support@tmra.ai'
      - DESTINATION_EMAILS='kpinc425@gmail.com;10geekjames@gmail.com'
    build:
      context: ./
      dockerfile: ./Dockerfile
    ports:
      - "5174:5174"    